### ISSUE TITLE
Dotnet solution does not work with Visual Studio 2019

### ISSUE THREAD

**Issue by srini1978** [Green-Software-Foundation/carbon-aware-sdk#34]
There is a configuration mismatch between .net 6 and Visual studio 2019 and hence the current solution does not compile with Visual Studio 2019.

Working on seeing if the proposed workarounds -https://docs.microsoft.com/en-us/answers/questions/620284/how-to-target-net-60-with-visual-studio-2019.html solve the issue

**Comment by srini1978** [comment]
@vaughanknight  Looks like .Net  6.0 SDK is no longer supported on Visual Studio 2019. The proposed workarounds do not work and based on what I read here -  https://stackoverflow.com/questions/69773547/visual-studio-2019-not-showing-net-6-framework  the support has been removed.

We need to ask users to use Visual Studio 2022 only

**Comment by srini1978** [comment]
Dotnet solution will not work with Visual studio 2019 as .Net 6.0 is not supported on Visual studio 2019

**Comment by vaughanknight** [comment]
We want to be using .Net 6.0 since it's much faster, efficient, and lower carbon footprint.  It will still build in VS Code, command line, and the CLI and WebApi projects will build out of containers soon (work being done in a branch).

We should add some guidance to the "getting started" documentation as VS2022 is new, and .NET 6.0 gives a lot of performance gains aswell as mechanisms to clean up the code signficiantly.
