### ISSUE TITLE
[ADR Review]: Review of ADRs

### ISSUE THREAD

**Issue by Willmish** [Green-Software-Foundation/carbon-aware-sdk#351]
### What happened?

This is to track the review of the following ADRs:

- [ ] Dynamic Data Source Registration https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/architecture/decisions/0014-dynamic-datasource-registration.md (related to yet unimplemented: https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/architecture/decisions/0006-data-source-registration.md)
- [ ] Add option to display CLI output in CSV format https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/docs/architecture/decisions/0015-cli-output-csv.md

These ADRs are to be reviewed independently but discussion can be on this thread. If members have discussions via Zoom/Teams/etc outputs from those discussions must be put in this thread as they relate to the reviews.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Willmish** [comment]
Worth adding here the previously lead discussions under the PRs for proposing these ADRs:
 - Dynamic Data Source Registration: https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/288
 - Add option to display CLI output in CSV format https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/310
 
 @bderusha feel free to reiterate your thoughts here for increased visability.

**Comment by YaSuenag** [comment]
I think ADR-0014 (Dynamic Data Souce Registration) relates to #345 . 

#345 propose to support multiple data source in config JSON, but I think it affects to ADR-0014 because current implementation handles data source as a singleton. I think it is better to discuss more to reorganize related ADRs.

**Comment by bderusha** [comment]
**ADR-0015**
I would prefer this ADR to be more opinionated before it is approved or denied. 

- Either to propose a 3rd party CSV dependency or outline requirements for building the functionality needed to support this new feature.
- For forecasting data format I think that having a row for each flattened `ForecastData` value and a column for each flattened `OptimalDataPoint` value is a more user-friendly format. Specifically, putting the OptimalDataPoints at the end so that it's easier to manage them since the first 10 columns will always be the same, and the remaining columns can be parsed programmatically. EG:

| RequestedAt | Location | ... | ForecastDataTime | ForecastDataRating | OptimalTime_0 | OptimalRating_0 | OptimalTime_1 | OptimalRating_1 |
|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|----------------|
| 2023-04-01T00:00:00Z | EastUS | ... | 2023-04-01T01:00:00Z | 123 | 2023-04-01T01:00:00Z | 123 | 2023-04-01T02:00:00Z | 123 | 
| 2023-04-01T00:00:00Z | EastUS | ... | 2023-04-01T02:00:00Z | 123 | 2023-04-01T01:00:00Z | 123 | 2023-04-01T02:00:00Z | 123 | 
| 2023-04-01T00:00:00Z | EastUS | ... | 2023-04-01T03:00:00Z | 456 | 2023-04-01T01:00:00Z | 123 | 2023-04-01T02:00:00Z | 123 |

**Comment by Willmish** [comment]
Decision during meeting #355 - postponing decision by one week giving people more time to review
