### ISSUE TITLE
.NET8 blog article

### ISSUE THREAD

**Issue by Sophietn** [Green-Software-Foundation/carbon-aware-sdk#501]
**What:** A blog article outlining everything the Carbon Aware SDK team did for the .NET8 upgrade to the Carbon Aware SDK toolkit. Written by NTT DATA (who largely completed the work needed for the .NET8 upgrade)
**Why:** A celebration of the archivement, useful resource for others wanting to upgrade, recognises NTT DATA's contributions to the CA SDK and their adoption. 
**SoW:** 

- Define what the article should contain 
- Draft the article
- Review the article 
- Publish the article

**Comment by YaSuenag** [comment]
.NET 8 upgrade is a significant work by @tiwatsuka from NTT .  
So I'd like to contribute an article with him. @nttDamien from NTT DATA will support our work.

> Define what the article should contain

@Sophietn How about the following? Please give me your feedback.

1. Why we need .NET 8?
2. What it takes to upgrade to .NET 8
3. Unexpected work items
    * Testcase update for Azure Functions
    * Breaking changes about port number of ASP.NET
    * Fix build pipeline on GitHub Actions
4. Use cases in NTT / NTT DATA after .NET 8 upgrade

**Comment by Sophietn** [comment]
Thank you! @YaSuenag 
This looks like a good structure to me.
Looking forward to reviewing the article you draft.

**Comment by YaSuenag** [comment]
@Sophietn @vaughanknight @danuw 
I share the article of .NET8 migration work on CASDK. Can you review?
This article is written by @tiwatsuka , @nttDamien , and me.

Carbon Aware SDK 1.4, behind the scenes
===
As most software nowadays, the Carbon Aware SDK relies on a stack of utilities, and while adding a new feature is usually the most appealing for a project, it’s also critical to maintain the stack, especially in a community effort.

Containerization has helped shifting the upgrading work to a more convenient time for the development team, but there are still various motivation for keeping a stack up to date with current versions: security, bug fixes, performance, support… but the best it to couple with new feature development: such was the case for .NET framework.

However, those updates often have ripple effects, as their dependencies are not always foreseeable, making software upgrade workload hard to predict.

As NTT and NTT DATA were key participants in this contribution, this is a good occasion to cast a light on the behind the scenes, and the way this new Carbon Aware SDK is being used internally.

# Why .NET 8 ?

Carbon Aware SDK v1.4.0 was released on May 2024, its core evolution was the upgrade to .NET 8. Until v1.3.x, the Carbon Aware SDK has relied on the LTS (Long Term Support) version .NET 6. With an EOL (End of Life) set for November 2024, an upgrade was unavoidable.

Microsoft released .NET 8 in Nov 2023, this is the latest LTS version of .NET and [will be supported until Nov 2026](https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core). 

Wanting to display the Carbon Intensity metrics from the Carbon Aware SDK WebAPI, made .NET 8 a requirement, as .NET 8 introduced an [enhanced supports for implementing metrics features](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8/runtime#extensions-metrics).

Indeed, the newly introduced [IMeterFactory](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.metrics.imeterfactory?view=net-8.0) interface enabled us to create a [Meter](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.metrics.meter?view=net-8.0) instance while maintaining modularity by using dependency injection (i.e. use the .NET 8 implementation of the feature, instead of recreating it… another software development sustainable pattern). 

In summary, Carbon Intensity metrics handling was combined with the necessary support extension that .NET 8 upgrade provides.

# In practice

The initial work for upgrading to .NET 8 was done in [Pull Request #404](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/404) (aka PR, basically a code change proposal, which once approved will be merged in the main code).

Without being a C# expert, it’s still interesting to look at the PR and see that: it involves several individuals working together as a community, many files were impacted, tests and samples are as critical as they should.

For the nitty gritty (else jump to the next paragraph): the core work is “simply” updating the target framework version. 

It can be done in the property window of each C# projects, for example in the Japanese version of Visual Studio (Fig.1).

![fig1](https://github.com/Green-Software-Foundation/carbon-aware-sdk/assets/7421132/5ddc757b-0321-4aa7-9ad1-69c4c4f746f9)

Fig.1 Property window of C# project in Carbon Aware SDK on Visual Studio Community Edition

Carbon Aware SDK includes 30 C# projects (in v1.3.0 at least), so automation is welcomed. The target framework version is described in `/Project/PropertyGroup/TargetFramework` in `.csproj` file. For example, running the command on WSL:

```
find . -name "*.csproj" -exec sed -i 's|^\(\s\+\)<TargetFramework>net6.0</TargetFramework>$|\1<TargetFramework>net8.0</TargetFramework>|g' {} \;
```

.NET version is specified in many other places, which need to be updated as well (`grep` will list them all).

* Base image in Docker file
    * Use tag `8.0` instead of `6.0` for `mcr.microsoft.com/dotnet/sdk`
* Tool configurations
    * global.json
    * dotnet-tools.json
    * launch.json for VSCode
* Target framework version for OpenAPI generator for .NET
* .NET version for [actions/setup-dotnet](https://github.com/actions/setup-dotnet) in GitHub Actions Workflow
* Comments in source files
* Documents

While the updating part is done, the work does not end there…

# Unexpected work items

While the .NET 8 upgrade was done, some unexpected issues surfaced. 

## Ripple effect on sample code

To help onboard new comers to the Carbon Aware SDK, a sample running on Azure Functions is provided.

Azure Functions for .NET is transitioning one of its execution modes (the In-process model) for the Isolated worker model ([more details here](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-in-process-differences)). Moreover, .NET 8 did not provide yet an option to use the former model in its initial release (cf. [roadmap of Azure Functions](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/net-on-azure-functions-august-2023-roadmap-update/ba-p/3910098)).

As our sample was still implementing the in-process model (to be deprecated and not available in .NET 8 at this time), it made sense to migrate to the isolated worker model.

For the code lover, there is an helpful [guide](https://learn.microsoft.com/en-us/azure/azure-functions/migrate-dotnet-to-isolated-model?tabs=net8) for the migration. This led to:

* Change the version of container images to build and test
* Update the `.csproj` file
* Replace `Startup.cs` with `Program.cs`
* Replace `FunctionName` attribute with `Function`
* Change loggers to be obtained from the DI container
* Update the document

For more details browse: [Pull Request #420](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/420).

## Port Number Breaking change

As Carbon Aware SDK WebAPI uses ASP.NET Core technology another collateral must do change was required since .NET 8 changed its default port number from 80 to 8080 [Microsoft Learn document](https://learn.microsoft.com/en-us/dotnet/core/compatibility/containers/8.0/aspnet-port)).

Changing the port number from WebAPI container, which affects the containerPort in Helm chart and some GitHub Workflows which uses WebAPI.

## Broken build pipeline on GitHub Actions

Thanks to GitHub, a lot of automation is available in order to publish code, allowing to focus more on coding, in particular the Carbon Aware SDK repository is configured to publish WebAPI container image (like a snapshot build) when a commit occurs on the dev branch. 

However, it suddenly stopped working after .NET 8 upgrade.

The team investigated the logs (Fig. 2), as a container image for both AMD64 and Arm64 Linux in GitHub Actions with [docker/build-push-action](https://github.com/docker/build-push-action): a mysterious segmentation fault (SEGV) was occurring after the upgrade… the code was not changed,  `dotnet publish` was outside the scope.

```
 > [linux/arm64 build-env 4/6] RUN dotnet publish CarbonAware.WebApi/src/CarbonAware.WebApi.csproj -c Release -o publish:
7.209 MSBuild version 17.9.6+a4ecab324 for .NET
24.69   Determining projects to restore...
41.42 Segmentation fault (core dumped)
```

Fig.2 Logs in `dotnet publish` on GitHub Actions

Further investigation was done, and thanks to a [.NET blog](https://devblogs.microsoft.com/dotnet/improving-multiplatform-container-support/), about multi-platform container support, that an unsupported approach was used for the build, and needed to be amended. More precisely, since .NET 6, QEMU static binaries were used to build container image for multi platforms.

Fortunately .NET blog guides how to build multi platform container images, and the workflow was fixed accordingly in [Pull Request #498](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pull/498). So WebAPI container image with .NET 8 can be pulled from [GitHub Packages](https://github.com/Green-Software-Foundation/carbon-aware-sdk/pkgs/container/carbon-aware-sdk) now!

# Use case in NTT / NTT DATA

While NTT & NTT DATA have been contributing to the Carbon Aware SDK a long time, none appeared in the [adopters list](https://github.com/Green-Software-Foundation/carbon-aware-sdk/blob/dev/casdk-docs/docs/overview/adopters.md), it is now changed thanks to those uses cases.

## Carbon Intensity map

Thanks to the new Carbon Aware SDK v1.4.0 carbon metrics exporter (thanks to .NET 8), more visualization capability are reachable.

This feature facilitate integration with monitoring solutions like [Prometheus](https://prometheus.io/) and furthermore with a visualization solution like [Grafana](https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/): unlocking geomap style visualization (showing metrics at specified locations on a map). By enabling the exporter and making some settings on Grafana, carbon intensities can be exported from Carbon Aware SDK to a geomap, this is part of a dashboard to monitor carbon emissions for software systems.

![fig3](https://github.com/Green-Software-Foundation/carbon-aware-sdk/assets/7421132/84092a1b-bd10-48cf-96e1-62674e5b2aee)

## Green Dashboard for Kubernetes

Carbon Aware SDK helps increase awareness around Carbon emission, and it is now possible to monitor carbon emission per application within Kubernetes.

In practice, each container energy consumption is evaluated through [Kepler](https://www.cncf.io/projects/kepler/) (sandbox project in Cloud Native Cloud Foundation, [CNCF](https://www.cncf.io/)), and thanks to the Carbon Aware SDK, the carbon emission can be evaluated.

All those emission data from power grid can be accessed through Prometheus exporter with Carbon Aware SDK (starting v1.4.0), and a visualized with Grafana dashboard.

The power consumption, energy consumption, carbon emission, and SCI (Software Carbon Intensity) can be seen at a glance!

![fig4](https://github.com/Green-Software-Foundation/carbon-aware-sdk/assets/7421132/c1fd9cc6-ee00-41f3-b538-a1fb4dfdacfd)

**Comment by danuw** [comment]
awesome @YaSuenag and team - can we also get that into the blog please? https://github.com/Green-Software-Foundation/carbon-aware-sdk/tree/dev/casdk-docs/blog


will review later and come with feedback if I have any

**Comment by nttDamien** [comment]
Hi,

Thanks a lot for your review and comments. WIth Suenaga san, we posted some reply to the comments.

Looking forward,
Damien
________________________________

**Comment by nttDamien** [comment]
[like]  TIG ＲＯＵＸ Ｄａｍｉｅｎ/Roux, Damien (... reacted to your message:
________________________________

**Comment by NAMRATA-WOKE** [comment]
@danuw have you had a chance to review and offer any feedback? https://docs.google.com/document/d/1bM7xCDj3tXDQL-TYCyX8hsdsnSLtRbTIDD4qF0Q1mf0/edit?usp=sharing

**Comment by danuw** [comment]
Done - sorry for delay - Great and only saw a possible typo in the last sentence which i flagged through a comment.

Thanks.

**Comment by NAMRATA-WOKE** [comment]
@Jenya-design can you create an image for this article? Use the [Google Doc](https://docs.google.com/document/d/1bM7xCDj3tXDQL-TYCyX8hsdsnSLtRbTIDD4qF0Q1mf0/edit) as a reference.

**Comment by Jenya-design** [comment]
@NAMRATA-WOKE please check the cover attached and [on Drive](https://drive.google.com/drive/folders/1dxNGuLpcUBnTfobvXVBj_UfTE4oHPb60?usp=sharing)
![Image](https://github.com/user-attachments/assets/e4930840-6a94-4e1f-8927-39f3d8b371df)

**Comment by NAMRATA-WOKE** [comment]
Article is scheduled to be published Tuesday next week (Aug 13). Thanks everyone!

**Comment by NAMRATA-WOKE** [comment]
Hi all, please note the article has been published. Let me know if any changes are needed: https://greensoftware.foundation/articles/upgrading-to-net-8-inside-the-carbon-aware-sdk-v1-4

**Comment by nttDamien** [comment]
[celebrate]     TIG ＲＯＵＸ Ｄａｍｉｅｎ/Roux, Damien (... reacted to your message:
________________________________

**Comment by nttDamien** [comment]
Such a great news, thanks a lot !
________________________________

**Comment by YaSuenag** [comment]
Thanks a lot @NAMRATA-WOKE !!

BTW why screenshot of our dashboards in ".NET8 Upgrade in Action" have not posted?

**Comment by NAMRATA-WOKE** [comment]
@YaSuenag Thanks for bringing that to my attention. The images should appear now!
